### ISSUE TITLE
在B站迷路了

### ISSUE THREAD

**Issue by yushu200403** [ikun14514/liuying_GPT-SoVITS#2]
作者大大你的B站好像搜不到呢？是改名了嘛？
![image](https://github.com/user-attachments/assets/ee398a23-2405-4a19-99d9-7bb2416ef7a8)

**Comment by ikun14514** [comment]
改了 叫银氨络合物ag 去军训了 忘记管这个GitHub账号了（）

**Comment by ikun14514** [comment]
![image](https://github.com/user-attachments/assets/f004e5ef-7ba4-48f2-99a6-388d7c9fabc2)

**Comment by ikun14514** [comment]
@00000O00000
